name: news_aggregator
description: A News Aggregator App built with Flutter and GetX
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  get: ^4.6.6
  http: ^1.1.0
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    # Comment out the images directory since we don't have any images yet
    # - assets/images/